name: Publish

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

env:
  SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
  SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
  SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
  OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  STAGING_PROFILE_ID: ${{ secrets.STAGING_PROFILE_ID }}

jobs:
  publish:
    name: Release build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17

      - name: Check out material-components-android
        uses: actions/checkout@v3
        with:
          repository: UdaraWanasinghe/material-components-android
          ref: release-1.12-hotfix
          path: material-components-android

      - name: Check out android-version-catalog
        uses: actions/checkout@v3
        with:
          repository: UdaraWanasinghe/android-version-catalog
          ref: v1.0.1
          token: ${{ secrets.VERSION_CATALOG_ACCESS_TOKEN }}
          path: android-version-catalog

      - name: Check out common-gradle-plugins
        uses: actions/checkout@v3
        with:
          repository: UdaraWanasinghe/common-gradle-plugins
          ref: v1.0.0
          token: ${{ secrets.COMMON_GRADLE_PLUGINS_ACCESS_TOKEN }}
          path: common-gradle-plugins

      - name: Check out android-extensions
        uses: actions/checkout@v3
        with:
          path: android-extensions
          ref: v1.0.6

      - name: Check out android-providerfile
        uses: actions/checkout@v3
        with:
          repository: UdaraWanasinghe/android-providerfile
          ref: v1.0.1
          token: ${{ secrets.PROVIDERFILE_ACCESS_TOKEN }}
          path: android-providerfile

      - name: Publish material-components-android
        working-directory: material-components-android
        run: ./gradlew publishToMavenLocal

      - name: Publish android-version-catalog
        working-directory: android-version-catalog
        run: ./gradlew publishToMavenLocal

      - name: Publish common-gradle-plugins
        working-directory: common-gradle-plugins
        run: ./gradlew publishToMavenLocal

      - name: Publish android-providerfile
        working-directory: android-providerfile
        run: ./gradlew publishToMavenLocal

      - name: Release build android-extensions
        working-directory: android-extensions
        run: ./gradlew :extensions:assembleRelease

      - name: Publish android-extensions to MavenCentral
        working-directory: android-extensions
        run: ./gradlew publishReleasePublicationToSonatypeRepository --max-workers 1 closeAndReleaseSonatypeStagingRepository
