name: Publish

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish:
    name: Release build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17

      - name: Check out version-catalog
        run: |
          git clone https://${{ github.actor }}:${{ secrets.VERSION_CATALOG_ACCESS_TOKEN }}@github.com/UdaraWanasinghe/android-version-catalog $GITHUB_WORKSPACE/version-catalog
        shell: bash

      - name: Check out android-extensions
        uses: actions/checkout@v3
        with:
          path: android-extensions

      - name: Publish version-catalog
        working-directory: version-catalog
        run: ./gradlew publishToMavenLocal

      - name: Release build android-extensions
        working-directory: android-extensions
        run: ./gradlew :extensions:assembleRelease

      - name: Publish android-extensions to MavenCentral
        working-directory: android-extensions
        run: ./gradlew publishReleasePublicationToSonatypeRepository --max-workers 1
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}